/**
 * Password rules, in one place.
 *
 * Imported by both the Server Action that enforces them and the form that
 * hints at them — they were duplicated as bare numbers in four spots, which is
 * how a client saying "min 10" ends up next to a server accepting 8.
 */

export const MIN_PASSWORD = 8

/**
 * Deliberately only a length check.
 *
 * Symbols are never rejected: forbidding them shrinks the search space and
 * breaks anything generated by a password manager, which is where these will
 * live. Composition rules ("must contain a digit") are not applied either —
 * for four people sharing a private trip app they add friction and no real
 * strength, and length is what actually matters.
 */
export function passwordProblem(password: string): string | null {
  if (password.length < MIN_PASSWORD) {
    return `Password must be at least ${MIN_PASSWORD} characters.`
  }
  return null
}
